using System.Text;
using TrendsTracker.Models;

namespace TrendsTracker.Reporting;

/// <summary>
/// STAGE 5 — REPORT.
/// Renders the pipeline output to the console and to a timestamped Markdown file.
/// Every report carries a prominent "not investment advice" disclaimer.
/// </summary>
public static class ReportWriter
{
    private const string Disclaimer =
        "This report is generated by an automated research assistant from public news and " +
        "company documents. It is NOT investment advice, a recommendation, or a prediction. " +
        "Media attention is often a lagging signal. Do your own research and consult a " +
        "SEBI-registered advisor before investing.";

    public static void WriteConsole(TrendReport report)
    {
        Console.WriteLine();
        Console.WriteLine("================ TREND REPORT ================");
        Console.WriteLine($"Generated : {report.GeneratedAt:yyyy-MM-dd HH:mm}");
        Console.WriteLine($"Articles  : {report.ArticlesAnalyzed}");
        Console.WriteLine();

        Console.WriteLine("--- Trending Themes (ranked) ---");
        if (report.Themes.Count == 0)
            Console.WriteLine("  (none detected)");
        foreach (var t in report.Themes)
        {
            var flags = new List<string>();
            if (t.GovernmentDriven) flags.Add("GOVT");
            if (t.UsToIndiaPattern) flags.Add("US→IN");
            var flagStr = flags.Count > 0 ? $" [{string.Join(",", flags)}]" : "";
            Console.WriteLine($"  • {t.Name}{flagStr}  (freq {t.Frequency}, mom {t.Momentum}, score {t.Score:F0})");
        }

        Console.WriteLine();
        Console.WriteLine("--- Companies confirmed via concall / investor docs ---");
        var confirmed = report.Confirmations
            .Where(c => c.DocumentsFound && c.LongTermGrowthClaimed)
            .OrderByDescending(c => c.Confidence)
            .ToList();

        if (confirmed.Count == 0)
        {
            Console.WriteLine("  (no companies passed the document-backed growth check)");
        }
        else
        {
            foreach (var c in confirmed)
                Console.WriteLine($"  ✓ {c.Company.Name} [{c.Company.ThemeName}] — confidence {c.Confidence}");
        }

        Console.WriteLine();
        Console.WriteLine("DISCLAIMER: " + Disclaimer);
        Console.WriteLine("==============================================");
    }

    public static string WriteMarkdown(TrendReport report, string outputDir)
    {
        Directory.CreateDirectory(outputDir);
        var file = Path.Combine(outputDir, $"trend-report-{report.GeneratedAt:yyyyMMdd-HHmmss}.md");

        var sb = new StringBuilder();
        sb.AppendLine("# Trend Report");
        sb.AppendLine();
        sb.AppendLine($"- **Generated:** {report.GeneratedAt:yyyy-MM-dd HH:mm}");
        sb.AppendLine($"- **Articles analysed:** {report.ArticlesAnalyzed}");
        sb.AppendLine();

        sb.AppendLine("## Trending Themes");
        sb.AppendLine();
        if (report.Themes.Count == 0)
        {
            sb.AppendLine("_No themes detected._");
        }
        else
        {
            sb.AppendLine("| Theme | Freq | Momentum | Govt | US→IN | Score | Rationale |");
            sb.AppendLine("|---|---|---|---|---|---|---|");
            foreach (var t in report.Themes)
            {
                sb.AppendLine($"| {Escape(t.Name)} | {t.Frequency} | {t.Momentum} | " +
                              $"{(t.GovernmentDriven ? "yes" : "")} | {(t.UsToIndiaPattern ? "yes" : "")} | " +
                              $"{t.Score:F0} | {Escape(t.Rationale)} |");
            }
        }
        sb.AppendLine();

        sb.AppendLine("## Companies — Document-Backed Growth Check");
        sb.AppendLine();
        var grouped = report.Confirmations
            .OrderBy(c => c.Company.ThemeName)
            .ThenByDescending(c => c.Confidence);

        foreach (var c in grouped)
        {
            sb.AppendLine($"### {Escape(c.Company.Name)} ({Escape(c.Company.Exchange)}:{Escape(c.Company.Stock)})");
            sb.AppendLine($"- **Theme:** {Escape(c.Company.ThemeName)}");
            sb.AppendLine($"- **Why relevant:** {Escape(c.Company.WhyRelevant)}");
            sb.AppendLine($"- **Documents found:** {(c.DocumentsFound ? "yes" : "no")}");
            sb.AppendLine($"- **Can revenue 2x+ in 3-5 years:** {(c.LongTermGrowthClaimed ? "yes" : "no")}");
            sb.AppendLine($"- **Confidence:** {c.Confidence}/100");
            sb.AppendLine($"- **Verdict:** {Escape(c.Verdict)}");
            if (!string.IsNullOrWhiteSpace(c.GrowthSignal))
                sb.AppendLine($"- **Growth signal:** {Escape(c.GrowthSignal)}");
            if (!string.IsNullOrWhiteSpace(c.MarginSignal))
                sb.AppendLine($"- **Margin signal:** {Escape(c.MarginSignal)}");
            if (!string.IsNullOrWhiteSpace(c.ExpansionSignal))
                sb.AppendLine($"- **Expansion signal:** {Escape(c.ExpansionSignal)}");

            if (c.EvidenceQuotes.Count > 0)
            {
                sb.AppendLine("- **Evidence (management's own words):**");
                foreach (var q in c.EvidenceQuotes)
                    sb.AppendLine($"  > {Escape(q)}");
            }
            if (c.DocumentSources.Count > 0)
            {
                sb.AppendLine("- **Sources:**");
                foreach (var s in c.DocumentSources)
                    sb.AppendLine($"  - {s}");
            }
            sb.AppendLine();
        }

        sb.AppendLine("---");
        sb.AppendLine($"> **DISCLAIMER:** {Disclaimer}");

        File.WriteAllText(file, sb.ToString());
        return file;
    }

    private static string Escape(string s) =>
        string.IsNullOrEmpty(s) ? "" : s.Replace("|", "\\|").Replace("\n", " ").Replace("\r", " ");
}
